export const INCREASE_SECONDS = "INCREASE_SECONDS";

export const GET_NOT_FINISHED_EXECUTION = "GET_NOT_FINISHED_EXECUTION";

export const SET_EXECUTION = "SET_EXECUTION";

export const FINISH_EXECUTION = "FINISH_EXECUTION";
