export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_RESULT = "GET_CATEGORY_RESULT";

export const DELETE_TASKS_FROM_CATEGORY = "DELETE_TASKS_FROM_CATEGORY";
export const DELETE_TASK_FROM_CATEGORY = "DELETE_TASK_FROM_CATEGORY";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_RESULT = "DELETE_CATEGORY_RESULT";