export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_RESULT = "FETCH_CATEGORIES_RESULT";

export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_RESULT = "ADD_CATEGORY_RESULT";

export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_CATEGORY_RESULT = "EDIT_CATEGORY_RESULT";