export const GET_TASK = "GET_TASK";
export const GET_TASK_RESULT = "GET_TASK_RESULT";

export const EDIT_TASK = "EDIT_TASK";

export const DELETE_CURRENT_TASK = "DELETE_CURRENT_TASK";
export const DELETE_CURRENT_TASK_RESULT = "DELETE_CURRENT_TASK_RESULT";