export const GET_TASK = "GET_TASK";
export const SET_TASK = "SET_TASK";

export const EDIT_TASK = "EDIT_TASK";

export const DELETE_CURRENT_TASK = "DELETE_CURRENT_TASK";
export const DELETE_CURRENT_TASK_RESULT = "DELETE_CURRENT_TASK_RESULT";

export const EDIT_TIMELINE_ELEMENT = "EDIT_TIMELINE_ELEMENT";
export const EDIT_TIMELINE_ELEMENT_RESULT = "EDIT_TIMELINE_ELEMENT_RESULT";

export const GET_CATEGORY_TITLE = "GET_CATEGORY_TITLE";
export const SET_CATEGORY_TITLE = "SET_CATEGORY_TITLE";
